server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Angular Router necesita que cualquier ruta del frontend vuelva a index.html.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # En Docker, Nginx hace de puente hacia Django para /api y /media.
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        proxy_pass http://backend:8000/media/;
    }
}
