# Generated by Django 5.0.7 on 2026-04-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia',
            name='horario_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='schedules.horarioentry'),
        ),
        migrations.AlterUniqueTogether(
            name='ausencia',
            unique_together={('fecha', 'horario_entry')},
        ),
    ]
