# Generated by Django 5.0.7 on 2026-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=200)),
                ('curso', models.CharField(blank=True, default='', max_length=100)),
                ('aula', models.CharField(blank=True, default='', max_length=50)),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes')], max_length=1)),
                ('hora', models.PositiveSmallIntegerField(choices=[(1, 'Tramo 1'), (2, 'Tramo 2'), (3, 'Tramo 3'), (4, 'Tramo 4'), (5, 'Tramo 5'), (6, 'Tramo 6'), (7, 'Tramo 7'), (8, 'Tramo 8'), (9, 'Tramo 9'), (10, 'Tramo 10'), (11, 'Tramo 11'), (12, 'Tramo 12'), (13, 'Tramo 13'), (14, 'Tramo 14')])),
            ],
            options={
                'verbose_name': 'Entrada de horario',
                'verbose_name_plural': 'Entradas de horario',
                'ordering': ['dia', 'hora', 'profesor__nombre'],
            },
        ),
    ]
