# Generated by Django 5.0.7 on 2026-04-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioentry',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_entries', to='users.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioentry',
            unique_together={('profesor', 'dia', 'hora')},
        ),
    ]
