# Generated by Django 5.0.7 on 2026-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParteAusencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('A', 'Módulo A'), ('B', 'Módulo B')], max_length=1)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='partes/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Parte de ausencias',
                'verbose_name_plural': 'Partes de ausencias',
                'ordering': ['-fecha', 'tipo'],
                'unique_together': {('fecha', 'tipo')},
            },
        ),
    ]
