# Generated by Django 5.0.7 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteausencias',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('G', 'IES completo'),
                    ('A', 'Modulo A'),
                    ('B', 'Modulo B'),
                ],
                max_length=1,
            ),
        ),
    ]
